name: survey
description: Helen Now
homepage: https://github.com/mkaraki-helen/survey
version: 1.0.1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  device_info_plus: ^9.0.2
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
