name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v1
          with:
            java-version: '12.x'
        - uses: subosito/flutter-action@v1
          with:
            channel: 'stable'  
        - run: flutter pub get
        - name: Publish
          uses: k-paxian/dart-package-publisher@v1.5.1
          with:
            credentialJson: ${{ secrets.PUBDEV_SECRET }}
            flutter: true
            skipTests: true
